name = "Sai Ram Charan"
age = 24
height = 5.6
Male = True
print("My name is {} \nMy age is {} of height {}".format(name, age, height))

# Integer to String Conversion
print(type(age), age)
age = str(age)
print(type(age), age)
age = int(age)

# Integer to float conversion
print(type(age), age)
age = float(age)
print(type(age), age)
age = int(age)

# Integer to boolean conversion
print(type(age), age)
age = bool(age)
print(type(age), age)

# float to integer
print(type(height), height)
height = int(height)
print(type(height), height)
height = float(height)

# float to string
print(type(height), height)
height = str(height)
print(type(height), height)
height = float(height)

# float to bool
print(type(height), height)
height = bool(height)
print(type(height), height)

# bool to integer
print(type(Male), Male)
Male = int(Male)
print(type(Male), Male)
Male = bool(Male)

# bool to float
print(type(Male), Male)
Male = float(Male)
print(type(Male), Male)
Male = bool(Male)

# bool to string
print(type(Male), Male)
Male = str(Male)
print(type(Male), Male)

# string to boolean
print(type(name), name)
name = bool(name)
print(type(name), name)
# String to Integer is not possible unless the string is an integer like (age) in our program
# String to Float is not possible unless the String is a float like (height) in our program
